const copy = {
  en: {
    meta: "A calm, private baby sleep tracker with explainable wake-window guidance. Free, offline, and no account required.",
    skip: "Skip to content", brandProduct: "Baby Sleep", navHow: "How it works", navPrivacy: "Privacy", language: "Language",
    heroEyebrow: "Baby sleep, made calmer", heroTitle: "A clearer rhythm for baby sleep.", heroLede: "Track sleep in seconds and get a practical next-sleep window that explains what it used—without an account.",
    appStoreSmall: "Download on the", availability: "For iPhone and iPad", trustFree: "Free essentials", trustNoAccount: "No account required", trustOffline: "Works offline",
    floatTitle: "Built around your baby", floatBody: "Recent sleep shapes the estimate",
    proofFastTitle: "One-tap tracking", proofFastBody: "Start, stop, or add sleep later.", proofClearTitle: "Explainable guidance", proofClearBody: "See why the window moved.", proofPrivateTitle: "Private by default", proofPrivateBody: "Core tracking stays on device.",
    predictionEyebrow: "Guidance you can understand", predictionTitle: "A window, not a promise.", predictionBody: "Professor Ary combines age-based guidance with your baby’s recent sleep. As you log, it adapts—and shows the ingredients behind the estimate.", predictionPoint1: "A practical range instead of false precision", predictionPoint2: "Recent patterns get more weight", predictionPoint3: "Edit past sleep without losing control of the day", predictionNote: "You know your baby best. Guidance supports—not replaces—your judgement.",
    privacyEyebrow: "Useful before sign-up", privacyTitle: "Start now. Stay private.", privacyBody: "Free tracking and the best local estimate work without creating an account. Your core sleep data is stored on your device and keeps working offline.", privacyCard1Title: "No account wall", privacyCard1Body: "Track the first sleep immediately.", privacyCard2Title: "Offline ready", privacyCard2Body: "Night feeds do not need a signal.", privacyCard3Title: "Cloud is a choice", privacyCard3Body: "Sleep+ adds backup and family sync.", privacyCard4Title: "No ad profile", privacyCard4Body: "No third-party advertising SDKs.", readPrivacy: "Read the privacy policy →",
    plusEyebrow: "Sleep+ when your family needs more", plusTitle: "Shared context. Fewer handoff questions.", plusBody: "Keep the free local experience, then add backup, caregiver sync, longer history, widgets, and deeper insights with Sleep+.", plusCard1Title: "Backup and restore", plusCard1Body: "Protect the family sleep history.", plusCard2Title: "Owner + caregiver", plusCard2Body: "See the same timeline across devices.", plusCard3Title: "History and insights", plusCard3Body: "Review patterns beyond the last three days.", plusCard4Title: "Premium widgets", plusCard4Body: "Keep the next window close at hand.", plusFootnote: "Sleep+ is optional. Free tracking, offline use, and local prediction quality stay free.",
    faqTitle: "A few useful answers.", faq1Question: "Do I need an account?", faq1Answer: "No. Free tracking, offline use, and the local sleep estimate work without an account. An account is only needed for optional Sleep+ cloud and family features.", faq2Question: "Is the sleep window medical advice?", faq2Answer: "No. It is an estimate based on age guidance and the sleep you log. Use your judgement and contact a qualified health professional about health or safety concerns.", faq3Question: "What stays free?", faq3Answer: "One baby, unlimited start and stop, the best local estimate, today’s timeline, three visible days of history, one reminder, a basic widget, and offline use.", faq4Question: "Can another caregiver help?", faq4Answer: "Yes. Sleep+ can connect the owner and one caregiver so both can share the same baby timeline across devices.", faq5Question: "Can I correct a missed or mistimed sleep?", faq5Answer: "Yes. Add sleep later, edit start and end times, or adjust the current wake anchor. The app recalculates from the corrected timeline.",
    ctaEyebrow: "A calmer next step", ctaTitle: "Meet tonight with more context.", ctaBody: "Start free, without an account. Add Sleep+ only when backup, family sync, and deeper history earn their place.", footerNote: "Sleep guidance for everyday planning—not medical advice.", support: "Support", privacyPolicy: "Privacy policy",
    heroAlt: "The app showing an explainable next-sleep window", insightAlt: "The app showing a seven-day sleep insight", offlineAlt: "The app explaining offline use without an account", caregiverAlt: "The app showing caregiver synchronization", appStoreLabel: "View Professor Ary: Baby Sleep on the App Store"
  },
  ca: {
    meta: "Un registre de son del nadó tranquil i privat, amb orientació de finestres de vigília explicable. Gratuït, sense connexió i sense compte.",
    skip: "Ves al contingut", brandProduct: "Son del nadó", navHow: "Com funciona", navPrivacy: "Privacitat", language: "Idioma",
    heroEyebrow: "El son del nadó, amb més calma", heroTitle: "Un ritme més clar per al son del nadó.", heroLede: "Registra el son en segons i obtén una finestra pràctica per al pròxim son que explica què ha tingut en compte, sense crear cap compte.",
    appStoreSmall: "Descarrega a l’", availability: "Per a iPhone i iPad", trustFree: "Funcions essencials gratuïtes", trustNoAccount: "Sense compte obligatori", trustOffline: "Funciona sense connexió",
    floatTitle: "Pensat per al teu nadó", floatBody: "El son recent ajusta l’estimació",
    proofFastTitle: "Registre amb un toc", proofFastBody: "Inicia, atura o afegeix el son més tard.", proofClearTitle: "Orientació explicable", proofClearBody: "Entén per què ha canviat la finestra.", proofPrivateTitle: "Privat per defecte", proofPrivateBody: "El registre principal queda al dispositiu.",
    predictionEyebrow: "Orientació que pots entendre", predictionTitle: "Una finestra, no una promesa.", predictionBody: "Professor Ary combina orientació per edat amb el son recent del teu nadó. A mesura que registres, s’adapta i et mostra què hi ha darrere de l’estimació.", predictionPoint1: "Un interval pràctic en lloc d’una falsa precisió", predictionPoint2: "Els patrons recents tenen més pes", predictionPoint3: "Edita el son anterior sense perdre el fil del dia", predictionNote: "Tu coneixes millor el teu nadó. L’orientació ajuda, però no substitueix el teu criteri.",
    privacyEyebrow: "Útil abans de registrar-te", privacyTitle: "Comença ara. Mantén la privacitat.", privacyBody: "El registre gratuït i la millor estimació local funcionen sense crear cap compte. Les dades principals de son es desen al dispositiu i continuen funcionant sense connexió.", privacyCard1Title: "Sense mur de registre", privacyCard1Body: "Registra el primer son de seguida.", privacyCard2Title: "Preparat sense connexió", privacyCard2Body: "Les preses nocturnes no necessiten cobertura.", privacyCard3Title: "El núvol és opcional", privacyCard3Body: "Sleep+ afegeix còpia i sincronització familiar.", privacyCard4Title: "Sense perfil publicitari", privacyCard4Body: "Sense SDK de publicitat de tercers.", readPrivacy: "Llegeix la política de privacitat →",
    plusEyebrow: "Sleep+ quan la família necessita més", plusTitle: "Context compartit. Menys dubtes en el relleu.", plusBody: "Conserva l’experiència local gratuïta i afegeix còpia, sincronització amb un cuidador, més historial, ginys i estadístiques avançades amb Sleep+.", plusCard1Title: "Còpia i restauració", plusCard1Body: "Protegeix l’historial de son familiar.", plusCard2Title: "Titular + cuidador", plusCard2Body: "Compartiu la mateixa cronologia entre dispositius.", plusCard3Title: "Historial i estadístiques", plusCard3Body: "Revisa patrons més enllà dels últims tres dies.", plusCard4Title: "Ginys prèmium", plusCard4Body: "Tingues a mà la pròxima finestra.", plusFootnote: "Sleep+ és opcional. El registre, l’ús sense connexió i la qualitat de la predicció local continuen sent gratuïts.",
    faqTitle: "Algunes respostes útils.", faq1Question: "Necessito un compte?", faq1Answer: "No. El registre gratuït, l’ús sense connexió i l’estimació local funcionen sense compte. Només cal un compte per a les funcions opcionals de núvol i família de Sleep+.", faq2Question: "La finestra de son és consell mèdic?", faq2Answer: "No. És una estimació basada en orientació per edat i el son que registres. Fes servir el teu criteri i consulta un professional sanitari qualificat davant de dubtes de salut o seguretat.", faq3Question: "Què continua sent gratuït?", faq3Answer: "Un nadó, inici i aturada il·limitats, la millor estimació local, la cronologia d’avui, tres dies visibles d’historial, un recordatori, un giny bàsic i ús sense connexió.", faq4Question: "Pot ajudar un altre cuidador?", faq4Answer: "Sí. Sleep+ pot connectar el titular i un cuidador perquè tots dos comparteixin la mateixa cronologia del nadó entre dispositius.", faq5Question: "Puc corregir un son omès o mal registrat?", faq5Answer: "Sí. Afegeix-lo més tard, edita les hores d’inici i final o ajusta el punt de vigília actual. L’app recalcula la cronologia corregida.",
    ctaEyebrow: "Un pròxim pas més tranquil", ctaTitle: "Afronta aquesta nit amb més context.", ctaBody: "Comença gratis i sense compte. Afegeix Sleep+ només quan la còpia, la sincronització familiar i l’historial avançat et siguin útils.", footerNote: "Orientació del son per a la planificació diària; no és consell mèdic.", support: "Suport", privacyPolicy: "Política de privacitat",
    heroAlt: "L’app mostra una finestra explicable per al pròxim son", insightAlt: "L’app mostra una estadística de son de set dies", offlineAlt: "L’app explica l’ús sense connexió i sense compte", caregiverAlt: "L’app mostra la sincronització amb un cuidador", appStoreLabel: "Veure Professor Ary: Baby Sleep a l’App Store"
  },
  es: {
    meta: "Un registro de sueño del bebé tranquilo y privado, con ventanas de vigilia explicables. Gratis, sin conexión y sin cuenta.",
    skip: "Ir al contenido", brandProduct: "Sueño del bebé", navHow: "Cómo funciona", navPrivacy: "Privacidad", language: "Idioma",
    heroEyebrow: "El sueño del bebé, con más calma", heroTitle: "Un ritmo más claro para el sueño del bebé.", heroLede: "Registra el sueño en segundos y recibe una ventana práctica para el próximo sueño que explica qué ha tenido en cuenta, sin crear una cuenta.",
    appStoreSmall: "Descargar en el", availability: "Para iPhone y iPad", trustFree: "Funciones esenciales gratis", trustNoAccount: "Sin cuenta obligatoria", trustOffline: "Funciona sin conexión",
    floatTitle: "Pensado para tu bebé", floatBody: "El sueño reciente ajusta la estimación",
    proofFastTitle: "Registro con un toque", proofFastBody: "Inicia, detén o añade el sueño después.", proofClearTitle: "Orientación explicable", proofClearBody: "Entiende por qué cambió la ventana.", proofPrivateTitle: "Privado por defecto", proofPrivateBody: "El registro principal se queda en el dispositivo.",
    predictionEyebrow: "Orientación que puedes entender", predictionTitle: "Una ventana, no una promesa.", predictionBody: "Professor Ary combina orientación por edad con el sueño reciente de tu bebé. A medida que registras, se adapta y muestra los datos que hay detrás de la estimación.", predictionPoint1: "Un intervalo práctico en lugar de falsa precisión", predictionPoint2: "Los patrones recientes tienen más peso", predictionPoint3: "Edita sueños anteriores sin perder el control del día", predictionNote: "Tú conoces mejor a tu bebé. La orientación ayuda, pero no sustituye tu criterio.",
    privacyEyebrow: "Útil antes de registrarte", privacyTitle: "Empieza ya. Mantén tu privacidad.", privacyBody: "El registro gratuito y la mejor estimación local funcionan sin crear una cuenta. Los datos principales de sueño se guardan en tu dispositivo y siguen disponibles sin conexión.", privacyCard1Title: "Sin muro de registro", privacyCard1Body: "Registra el primer sueño al instante.", privacyCard2Title: "Preparado sin conexión", privacyCard2Body: "Las tomas nocturnas no necesitan cobertura.", privacyCard3Title: "La nube es opcional", privacyCard3Body: "Sleep+ añade copia y sincronización familiar.", privacyCard4Title: "Sin perfil publicitario", privacyCard4Body: "Sin SDK publicitarios de terceros.", readPrivacy: "Leer la política de privacidad →",
    plusEyebrow: "Sleep+ cuando tu familia necesita más", plusTitle: "Contexto compartido. Menos dudas en el relevo.", plusBody: "Conserva la experiencia local gratuita y añade copia, sincronización con un cuidador, más historial, widgets y estadísticas avanzadas con Sleep+.", plusCard1Title: "Copia y restauración", plusCard1Body: "Protege el historial de sueño familiar.", plusCard2Title: "Titular + cuidador", plusCard2Body: "Compartid la misma cronología entre dispositivos.", plusCard3Title: "Historial y estadísticas", plusCard3Body: "Revisa patrones más allá de los últimos tres días.", plusCard4Title: "Widgets prémium", plusCard4Body: "Ten a mano la próxima ventana.", plusFootnote: "Sleep+ es opcional. El registro, el uso sin conexión y la calidad de la predicción local siguen siendo gratuitos.",
    faqTitle: "Algunas respuestas útiles.", faq1Question: "¿Necesito una cuenta?", faq1Answer: "No. El registro gratuito, el uso sin conexión y la estimación local funcionan sin cuenta. Solo necesitas una para las funciones opcionales de nube y familia de Sleep+.", faq2Question: "¿La ventana de sueño es consejo médico?", faq2Answer: "No. Es una estimación basada en orientación por edad y el sueño que registras. Usa tu criterio y consulta a un profesional sanitario cualificado ante dudas de salud o seguridad.", faq3Question: "¿Qué sigue siendo gratis?", faq3Answer: "Un bebé, inicios y paradas ilimitados, la mejor estimación local, la cronología de hoy, tres días visibles de historial, un recordatorio, un widget básico y uso sin conexión.", faq4Question: "¿Puede ayudar otro cuidador?", faq4Answer: "Sí. Sleep+ puede conectar al titular y a un cuidador para que ambos compartan la misma cronología del bebé entre dispositivos.", faq5Question: "¿Puedo corregir un sueño omitido o mal registrado?", faq5Answer: "Sí. Añádelo después, edita las horas de inicio y fin o ajusta el punto de vigilia actual. La app recalcula la cronología corregida.",
    ctaEyebrow: "Un próximo paso más tranquilo", ctaTitle: "Afronta esta noche con más contexto.", ctaBody: "Empieza gratis y sin cuenta. Añade Sleep+ solo cuando la copia, la sincronización familiar y el historial avanzado te resulten útiles.", footerNote: "Orientación del sueño para la planificación diaria; no es consejo médico.", support: "Soporte", privacyPolicy: "Política de privacidad",
    heroAlt: "La app muestra una ventana explicable para el próximo sueño", insightAlt: "La app muestra una estadística de sueño de siete días", offlineAlt: "La app explica el uso sin conexión y sin cuenta", caregiverAlt: "La app muestra la sincronización con un cuidador", appStoreLabel: "Ver Professor Ary: Baby Sleep en el App Store"
  },
  "es-mx": {
    meta: "Un registro de sueño del bebé tranquilo y privado, con ventanas de vigilia explicables. Gratis, sin conexión y sin cuenta.",
    skip: "Ir al contenido", brandProduct: "Sueño del bebé", navHow: "Cómo funciona", navPrivacy: "Privacidad", language: "Idioma",
    heroEyebrow: "El sueño del bebé, con más calma", heroTitle: "Un ritmo más claro para el sueño de tu bebé.", heroLede: "Registra el sueño en segundos y recibe una ventana práctica para el próximo sueño que explica qué tomó en cuenta, sin crear una cuenta.",
    appStoreSmall: "Descárgala en el", availability: "Para iPhone y iPad", trustFree: "Funciones esenciales gratis", trustNoAccount: "Sin cuenta obligatoria", trustOffline: "Funciona sin conexión",
    floatTitle: "Pensada para tu bebé", floatBody: "El sueño reciente ajusta el cálculo",
    proofFastTitle: "Registro con un toque", proofFastBody: "Inicia, detén o agrega el sueño después.", proofClearTitle: "Orientación explicable", proofClearBody: "Entiende por qué cambió la ventana.", proofPrivateTitle: "Privado por defecto", proofPrivateBody: "El registro principal se queda en el dispositivo.",
    predictionEyebrow: "Orientación que puedes entender", predictionTitle: "Una ventana, no una promesa.", predictionBody: "Professor Ary combina orientación por edad con el sueño reciente de tu bebé. Mientras registras, se adapta y muestra los datos detrás del cálculo.", predictionPoint1: "Un rango práctico en lugar de falsa precisión", predictionPoint2: "Los patrones recientes tienen más peso", predictionPoint3: "Edita sueños anteriores sin perder el control del día", predictionNote: "Tú conoces mejor a tu bebé. La orientación ayuda, pero no sustituye tu criterio.",
    privacyEyebrow: "Útil antes de registrarte", privacyTitle: "Empieza ahora. Mantén tu privacidad.", privacyBody: "El registro gratis y el mejor cálculo local funcionan sin crear una cuenta. Los datos principales de sueño se guardan en tu dispositivo y siguen disponibles sin conexión.", privacyCard1Title: "Sin muro de registro", privacyCard1Body: "Registra el primer sueño al instante.", privacyCard2Title: "Lista sin conexión", privacyCard2Body: "Las tomas nocturnas no necesitan señal.", privacyCard3Title: "La nube es opcional", privacyCard3Body: "Sleep+ agrega respaldo y sincronización familiar.", privacyCard4Title: "Sin perfil publicitario", privacyCard4Body: "Sin SDK publicitarios de terceros.", readPrivacy: "Leer la política de privacidad →",
    plusEyebrow: "Sleep+ cuando tu familia necesita más", plusTitle: "Contexto compartido. Menos dudas al relevarse.", plusBody: "Conserva la experiencia local gratis y agrega respaldo, sincronización con un cuidador, más historial, widgets y estadísticas avanzadas con Sleep+.", plusCard1Title: "Respaldo y restauración", plusCard1Body: "Protege el historial de sueño familiar.", plusCard2Title: "Titular + cuidador", plusCard2Body: "Compartan la misma cronología entre dispositivos.", plusCard3Title: "Historial y estadísticas", plusCard3Body: "Revisa patrones más allá de los últimos tres días.", plusCard4Title: "Widgets prémium", plusCard4Body: "Ten a la mano la próxima ventana.", plusFootnote: "Sleep+ es opcional. El registro, el uso sin conexión y la calidad del cálculo local siguen siendo gratis.",
    faqTitle: "Algunas respuestas útiles.", faq1Question: "¿Necesito una cuenta?", faq1Answer: "No. El registro gratis, el uso sin conexión y el cálculo local funcionan sin cuenta. Solo necesitas una para las funciones opcionales de nube y familia de Sleep+.", faq2Question: "¿La ventana de sueño es consejo médico?", faq2Answer: "No. Es un cálculo basado en orientación por edad y el sueño que registras. Usa tu criterio y consulta a un profesional de la salud calificado ante dudas de salud o seguridad.", faq3Question: "¿Qué sigue siendo gratis?", faq3Answer: "Un bebé, inicios y paradas ilimitados, el mejor cálculo local, la cronología de hoy, tres días visibles de historial, un recordatorio, un widget básico y uso sin conexión.", faq4Question: "¿Puede ayudar otro cuidador?", faq4Answer: "Sí. Sleep+ puede conectar al titular y a un cuidador para que ambos compartan la misma cronología del bebé entre dispositivos.", faq5Question: "¿Puedo corregir un sueño omitido o mal registrado?", faq5Answer: "Sí. Agrégalo después, edita las horas de inicio y fin o ajusta el punto de vigilia actual. La app vuelve a calcular con la cronología corregida.",
    ctaEyebrow: "Un siguiente paso más tranquilo", ctaTitle: "Llega a esta noche con más contexto.", ctaBody: "Empieza gratis y sin cuenta. Agrega Sleep+ solo cuando el respaldo, la sincronización familiar y el historial avanzado te resulten útiles.", footerNote: "Orientación del sueño para la planeación diaria; no es consejo médico.", support: "Soporte", privacyPolicy: "Política de privacidad",
    heroAlt: "La app muestra una ventana explicable para el próximo sueño", insightAlt: "La app muestra una estadística de sueño de siete días", offlineAlt: "La app explica el uso sin conexión y sin cuenta", caregiverAlt: "La app muestra la sincronización con un cuidador", appStoreLabel: "Ver Professor Ary: Baby Sleep en el App Store"
  },
  fr: {
    meta: "Un suivi du sommeil de bébé calme et privé, avec des fenêtres d’éveil explicables. Gratuit, hors ligne et sans compte.",
    skip: "Aller au contenu", brandProduct: "Sommeil de bébé", navHow: "Fonctionnement", navPrivacy: "Confidentialité", language: "Langue",
    heroEyebrow: "Le sommeil de bébé, plus sereinement", heroTitle: "Un rythme plus clair pour le sommeil de bébé.", heroLede: "Suivez le sommeil en quelques secondes et obtenez une fenêtre pratique pour le prochain sommeil, avec une explication des données utilisées, sans créer de compte.",
    appStoreSmall: "Télécharger dans l’", availability: "Pour iPhone et iPad", trustFree: "Fonctions essentielles gratuites", trustNoAccount: "Aucun compte requis", trustOffline: "Fonctionne hors ligne",
    floatTitle: "Pensé pour votre bébé", floatBody: "Le sommeil récent affine l’estimation",
    proofFastTitle: "Suivi en un geste", proofFastBody: "Démarrez, arrêtez ou ajoutez un sommeil plus tard.", proofClearTitle: "Conseils explicables", proofClearBody: "Comprenez pourquoi la fenêtre a changé.", proofPrivateTitle: "Privé par défaut", proofPrivateBody: "Le suivi principal reste sur l’appareil.",
    predictionEyebrow: "Des conseils compréhensibles", predictionTitle: "Une fenêtre, pas une promesse.", predictionBody: "Professor Ary associe des repères liés à l’âge au sommeil récent de votre bébé. Au fil des saisies, l’estimation s’adapte et vous montre les éléments pris en compte.", predictionPoint1: "Une plage pratique plutôt qu’une fausse précision", predictionPoint2: "Les habitudes récentes ont plus de poids", predictionPoint3: "Modifiez un sommeil passé sans perdre le fil de la journée", predictionNote: "C’est vous qui connaissez le mieux votre bébé. Ces conseils accompagnent votre jugement, ils ne le remplacent pas.",
    privacyEyebrow: "Utile avant toute inscription", privacyTitle: "Commencez maintenant. Restez privé.", privacyBody: "Le suivi gratuit et la meilleure estimation locale fonctionnent sans créer de compte. Les données de sommeil principales sont stockées sur votre appareil et restent disponibles hors ligne.", privacyCard1Title: "Sans inscription forcée", privacyCard1Body: "Suivez le premier sommeil immédiatement.", privacyCard2Title: "Prêt hors ligne", privacyCard2Body: "Les biberons de nuit n’ont pas besoin de réseau.", privacyCard3Title: "Le cloud reste un choix", privacyCard3Body: "Sleep+ ajoute sauvegarde et partage familial.", privacyCard4Title: "Aucun profil publicitaire", privacyCard4Body: "Aucun SDK publicitaire tiers.", readPrivacy: "Lire la politique de confidentialité →",
    plusEyebrow: "Sleep+ quand la famille en a besoin", plusTitle: "Un contexte partagé. Moins de questions au relais.", plusBody: "Gardez l’expérience locale gratuite, puis ajoutez sauvegarde, partage avec un proche, historique étendu, widgets et analyses avancées avec Sleep+.", plusCard1Title: "Sauvegarde et restauration", plusCard1Body: "Protégez l’historique de sommeil familial.", plusCard2Title: "Titulaire + proche", plusCard2Body: "Partagez la même chronologie entre appareils.", plusCard3Title: "Historique et analyses", plusCard3Body: "Observez les tendances au-delà des trois derniers jours.", plusCard4Title: "Widgets premium", plusCard4Body: "Gardez la prochaine fenêtre à portée de main.", plusFootnote: "Sleep+ est facultatif. Le suivi, l’utilisation hors ligne et la qualité de la prédiction locale restent gratuits.",
    faqTitle: "Quelques réponses utiles.", faq1Question: "Ai-je besoin d’un compte ?", faq1Answer: "Non. Le suivi gratuit, l’utilisation hors ligne et l’estimation locale fonctionnent sans compte. Un compte est uniquement nécessaire pour les fonctions cloud et familiales facultatives de Sleep+.", faq2Question: "La fenêtre de sommeil est-elle un avis médical ?", faq2Answer: "Non. C’est une estimation fondée sur des repères d’âge et le sommeil que vous saisissez. Faites preuve de discernement et consultez un professionnel de santé qualifié pour toute question de santé ou de sécurité.", faq3Question: "Qu’est-ce qui reste gratuit ?", faq3Answer: "Un bébé, démarrages et arrêts illimités, meilleure estimation locale, chronologie du jour, trois jours d’historique visibles, un rappel, un widget simple et utilisation hors ligne.", faq4Question: "Un autre proche peut-il aider ?", faq4Answer: "Oui. Sleep+ peut relier le titulaire et un proche afin qu’ils partagent la même chronologie de bébé entre leurs appareils.", faq5Question: "Puis-je corriger un sommeil oublié ou mal daté ?", faq5Answer: "Oui. Ajoutez-le plus tard, modifiez les heures de début et de fin ou ajustez le repère d’éveil actuel. L’app recalcule à partir de la chronologie corrigée.",
    ctaEyebrow: "Une prochaine étape plus sereine", ctaTitle: "Abordez ce soir avec plus de contexte.", ctaBody: "Commencez gratuitement, sans compte. Ajoutez Sleep+ seulement lorsque la sauvegarde, le partage familial et l’historique avancé vous sont utiles.", footerNote: "Des conseils de sommeil pour le quotidien, pas un avis médical.", support: "Assistance", privacyPolicy: "Politique de confidentialité",
    heroAlt: "L’app affiche une fenêtre explicable pour le prochain sommeil", insightAlt: "L’app affiche une analyse du sommeil sur sept jours", offlineAlt: "L’app explique l’utilisation hors ligne sans compte", caregiverAlt: "L’app affiche la synchronisation avec un proche", appStoreLabel: "Voir Professor Ary: Baby Sleep sur l’App Store"
  },
  de: {
    meta: "Ein ruhiger, privater Babyschlaf-Tracker mit nachvollziehbaren Wachfenstern. Kostenlos, offline und ohne Konto.",
    skip: "Zum Inhalt", brandProduct: "Babyschlaf", navHow: "So funktioniert’s", navPrivacy: "Datenschutz", language: "Sprache",
    heroEyebrow: "Babyschlaf, etwas gelassener", heroTitle: "Ein klarerer Rhythmus für Babyschlaf.", heroLede: "Erfasse Schlaf in Sekunden und erhalte ein praktisches Zeitfenster für den nächsten Schlaf – mit nachvollziehbarer Grundlage und ohne Konto.",
    appStoreSmall: "Laden im", availability: "Für iPhone und iPad", trustFree: "Kostenlose Basisfunktionen", trustNoAccount: "Kein Konto erforderlich", trustOffline: "Funktioniert offline",
    floatTitle: "Für dein Baby gemacht", floatBody: "Der letzte Schlaf prägt die Schätzung",
    proofFastTitle: "Erfassen mit einem Tipp", proofFastBody: "Schlaf starten, stoppen oder später eintragen.", proofClearTitle: "Nachvollziehbare Hinweise", proofClearBody: "Sieh, warum sich das Fenster verschoben hat.", proofPrivateTitle: "Standardmäßig privat", proofPrivateBody: "Die Kerndaten bleiben auf dem Gerät.",
    predictionEyebrow: "Hinweise, die du verstehst", predictionTitle: "Ein Zeitfenster, kein Versprechen.", predictionBody: "Professor Ary kombiniert altersbezogene Richtwerte mit dem letzten Schlaf deines Babys. Mit jedem Eintrag passt sich die Schätzung an und zeigt dir ihre Grundlage.", predictionPoint1: "Ein praktischer Bereich statt falscher Genauigkeit", predictionPoint2: "Aktuelle Muster werden stärker gewichtet", predictionPoint3: "Vergangenen Schlaf bearbeiten, ohne den Tagesüberblick zu verlieren", predictionNote: "Du kennst dein Baby am besten. Die Hinweise unterstützen dein Urteil, ersetzen es aber nicht.",
    privacyEyebrow: "Nützlich vor jeder Anmeldung", privacyTitle: "Sofort starten. Privat bleiben.", privacyBody: "Die kostenlose Erfassung und die beste lokale Schätzung funktionieren ohne Konto. Deine Kerndaten zum Schlaf werden auf deinem Gerät gespeichert und bleiben offline verfügbar.", privacyCard1Title: "Keine Kontoschranke", privacyCard1Body: "Erfasse den ersten Schlaf sofort.", privacyCard2Title: "Offline bereit", privacyCard2Body: "Nächtliches Füttern braucht kein Netz.", privacyCard3Title: "Cloud ist optional", privacyCard3Body: "Sleep+ ergänzt Backup und Familiensynchronisierung.", privacyCard4Title: "Kein Werbeprofil", privacyCard4Body: "Keine Werbe-SDKs von Drittanbietern.", readPrivacy: "Datenschutzerklärung lesen →",
    plusEyebrow: "Sleep+, wenn die Familie mehr braucht", plusTitle: "Gemeinsamer Überblick. Weniger Fragen bei der Übergabe.", plusBody: "Behalte die kostenlose lokale Erfahrung und ergänze mit Sleep+ Backup, Synchronisierung mit einer Betreuungsperson, längeren Verlauf, Widgets und tiefere Einblicke.", plusCard1Title: "Backup und Wiederherstellung", plusCard1Body: "Schütze den Schlafverlauf der Familie.", plusCard2Title: "Inhaber + Betreuungsperson", plusCard2Body: "Teilt dieselbe Zeitleiste auf mehreren Geräten.", plusCard3Title: "Verlauf und Einblicke", plusCard3Body: "Erkenne Muster über die letzten drei Tage hinaus.", plusCard4Title: "Premium-Widgets", plusCard4Body: "Behalte das nächste Fenster griffbereit.", plusFootnote: "Sleep+ ist optional. Erfassung, Offline-Nutzung und Qualität der lokalen Vorhersage bleiben kostenlos.",
    faqTitle: "Ein paar nützliche Antworten.", faq1Question: "Brauche ich ein Konto?", faq1Answer: "Nein. Kostenlose Erfassung, Offline-Nutzung und lokale Schlafschätzung funktionieren ohne Konto. Ein Konto brauchst du nur für die optionalen Cloud- und Familienfunktionen von Sleep+.", faq2Question: "Ist das Schlaffenster medizinischer Rat?", faq2Answer: "Nein. Es ist eine Schätzung auf Basis von Altersrichtwerten und dem erfassten Schlaf. Nutze dein eigenes Urteil und wende dich bei Gesundheits- oder Sicherheitsfragen an qualifiziertes medizinisches Fachpersonal.", faq3Question: "Was bleibt kostenlos?", faq3Answer: "Ein Baby, unbegrenztes Starten und Stoppen, beste lokale Schätzung, heutige Zeitleiste, drei sichtbare Verlaufstage, eine Erinnerung, ein Basis-Widget und Offline-Nutzung.", faq4Question: "Kann eine andere Betreuungsperson helfen?", faq4Answer: "Ja. Sleep+ verbindet den Inhaber mit einer Betreuungsperson, sodass beide dieselbe Baby-Zeitleiste auf ihren Geräten teilen.", faq5Question: "Kann ich vergessenen oder falsch erfassten Schlaf korrigieren?", faq5Answer: "Ja. Trage ihn später ein, bearbeite Start und Ende oder passe den aktuellen Wachzeit-Anker an. Die App berechnet die korrigierte Zeitleiste neu.",
    ctaEyebrow: "Ein gelassener nächster Schritt", ctaTitle: "Mit mehr Überblick in die Nacht.", ctaBody: "Starte kostenlos und ohne Konto. Ergänze Sleep+ erst, wenn Backup, Familiensynchronisierung und längerer Verlauf dir echten Nutzen bringen.", footerNote: "Schlafhinweise für die Alltagsplanung – kein medizinischer Rat.", support: "Support", privacyPolicy: "Datenschutzerklärung",
    heroAlt: "Die App zeigt ein nachvollziehbares Fenster für den nächsten Schlaf", insightAlt: "Die App zeigt eine siebentägige Schlafauswertung", offlineAlt: "Die App erklärt die Offline-Nutzung ohne Konto", caregiverAlt: "Die App zeigt die Synchronisierung mit einer Betreuungsperson", appStoreLabel: "Professor Ary: Baby Sleep im App Store ansehen"
  },
  "pt-br": {
    meta: "Um registro de sono do bebê tranquilo e privado, com janelas de vigília explicáveis. Grátis, offline e sem conta.",
    skip: "Ir para o conteúdo", brandProduct: "Sono do bebê", navHow: "Como funciona", navPrivacy: "Privacidade", language: "Idioma",
    heroEyebrow: "O sono do bebê, com mais calma", heroTitle: "Um ritmo mais claro para o sono do bebê.", heroLede: "Registre o sono em segundos e receba uma janela prática para o próximo sono, com os fatores usados no cálculo, sem criar uma conta.",
    appStoreSmall: "Baixar na", availability: "Para iPhone e iPad", trustFree: "Recursos essenciais grátis", trustNoAccount: "Sem conta obrigatória", trustOffline: "Funciona offline",
    floatTitle: "Feito para o seu bebê", floatBody: "O sono recente ajusta a estimativa",
    proofFastTitle: "Registro com um toque", proofFastBody: "Inicie, pare ou adicione o sono depois.", proofClearTitle: "Orientação explicável", proofClearBody: "Entenda por que a janela mudou.", proofPrivateTitle: "Privado por padrão", proofPrivateBody: "O registro principal fica no aparelho.",
    predictionEyebrow: "Orientação que você entende", predictionTitle: "Uma janela, não uma promessa.", predictionBody: "O Professor Ary combina orientações por idade com o sono recente do seu bebê. Conforme você registra, a estimativa se adapta e mostra os fatores considerados.", predictionPoint1: "Uma faixa prática em vez de falsa precisão", predictionPoint2: "Padrões recentes recebem mais peso", predictionPoint3: "Edite sonos anteriores sem perder o controle do dia", predictionNote: "Você conhece melhor o seu bebê. A orientação apoia, mas não substitui, o seu julgamento.",
    privacyEyebrow: "Útil antes do cadastro", privacyTitle: "Comece agora. Continue no controle.", privacyBody: "O registro gratuito e a melhor estimativa local funcionam sem criar uma conta. Os principais dados de sono ficam armazenados no seu aparelho e continuam disponíveis offline.", privacyCard1Title: "Sem barreira de cadastro", privacyCard1Body: "Registre o primeiro sono imediatamente.", privacyCard2Title: "Pronto para uso offline", privacyCard2Body: "Mamadas noturnas não precisam de sinal.", privacyCard3Title: "A nuvem é opcional", privacyCard3Body: "O Sleep+ adiciona backup e sincronização familiar.", privacyCard4Title: "Sem perfil de anúncios", privacyCard4Body: "Sem SDKs de publicidade de terceiros.", readPrivacy: "Ler a política de privacidade →",
    plusEyebrow: "Sleep+ quando a família precisar de mais", plusTitle: "Contexto compartilhado. Menos dúvidas na troca de turno.", plusBody: "Mantenha a experiência local gratuita e adicione backup, sincronização com um cuidador, histórico maior, widgets e análises avançadas com o Sleep+.", plusCard1Title: "Backup e restauração", plusCard1Body: "Proteja o histórico de sono da família.", plusCard2Title: "Titular + cuidador", plusCard2Body: "Compartilhem a mesma linha do tempo entre aparelhos.", plusCard3Title: "Histórico e análises", plusCard3Body: "Veja padrões além dos últimos três dias.", plusCard4Title: "Widgets premium", plusCard4Body: "Mantenha a próxima janela por perto.", plusFootnote: "O Sleep+ é opcional. O registro, o uso offline e a qualidade da previsão local continuam grátis.",
    faqTitle: "Algumas respostas úteis.", faq1Question: "Preciso de uma conta?", faq1Answer: "Não. O registro gratuito, o uso offline e a estimativa local funcionam sem conta. Uma conta só é necessária para os recursos opcionais de nuvem e família do Sleep+.", faq2Question: "A janela de sono é uma orientação médica?", faq2Answer: "Não. É uma estimativa baseada em orientações por idade e no sono registrado. Use o seu julgamento e consulte um profissional de saúde qualificado sobre questões de saúde ou segurança.", faq3Question: "O que continua grátis?", faq3Answer: "Um bebê, inícios e paradas ilimitados, a melhor estimativa local, a linha do tempo de hoje, três dias visíveis de histórico, um lembrete, um widget básico e uso offline.", faq4Question: "Outro cuidador pode ajudar?", faq4Answer: "Sim. O Sleep+ pode conectar o titular a um cuidador para que os dois compartilhem a mesma linha do tempo do bebê entre aparelhos.", faq5Question: "Posso corrigir um sono esquecido ou com horário errado?", faq5Answer: "Sim. Adicione-o depois, edite os horários de início e fim ou ajuste o ponto atual de vigília. O app recalcula usando a linha do tempo corrigida.",
    ctaEyebrow: "Um próximo passo mais tranquilo", ctaTitle: "Chegue à noite com mais contexto.", ctaBody: "Comece grátis e sem conta. Adicione o Sleep+ apenas quando backup, sincronização familiar e histórico avançado fizerem sentido para você.", footerNote: "Orientações de sono para o planejamento diário; não são aconselhamento médico.", support: "Suporte", privacyPolicy: "Política de privacidade",
    heroAlt: "O app mostra uma janela explicável para o próximo sono", insightAlt: "O app mostra uma análise de sono de sete dias", offlineAlt: "O app explica o uso offline e sem conta", caregiverAlt: "O app mostra a sincronização com um cuidador", appStoreLabel: "Ver Professor Ary: Baby Sleep na App Store"
  }
};

const supported = Object.keys(copy);
const params = new URLSearchParams(window.location.search);
const requested = (params.get("lang") || navigator.language || "en").toLowerCase();
const initialLocale = supported.includes(requested)
  ? requested
  : supported.includes(requested.split("-")[0])
    ? requested.split("-")[0]
    : "en";

const select = document.getElementById("locale-select");

function applyLocale(locale, updateUrl = false) {
  const strings = copy[locale] || copy.en;
  document.documentElement.lang = locale;
  document.title = `Professor Ary: Baby Sleep — ${strings.heroTitle}`;
  document.querySelector('meta[name="description"]').setAttribute("content", strings.meta);
  document.querySelector('meta[property="og:description"]').setAttribute("content", strings.meta);
  document.querySelectorAll("[data-copy]").forEach((element) => {
    const value = strings[element.dataset.copy];
    if (value) element.textContent = value;
  });
  document.querySelectorAll("[data-screen]").forEach((image) => {
    image.src = `assets/landing/${locale}-screen-${image.dataset.screen}.webp`;
  });
  const imageAlts = [strings.heroAlt, strings.insightAlt, strings.offlineAlt, strings.caregiverAlt];
  document.querySelectorAll("[data-screen]").forEach((image, index) => { image.alt = imageAlts[index]; });
  document.querySelectorAll("[data-app-store-link]").forEach((link) => { link.setAttribute("aria-label", strings.appStoreLabel); });
  document.querySelectorAll("[data-support-link]").forEach((link) => { link.href = `../${locale}/support`; });
  document.querySelectorAll("[data-privacy-link]").forEach((link) => { link.href = `../${locale}/privacy-policy`; });
  select.value = locale;
  if (updateUrl) {
    const url = new URL(window.location.href);
    url.searchParams.set("lang", locale);
    window.history.replaceState({}, "", url);
  }
}

select.addEventListener("change", (event) => applyLocale(event.target.value, true));
document.getElementById("year").textContent = new Date().getFullYear();
applyLocale(initialLocale);
